/**
 * Batch scan S&P 100 domains and write results to src/data/sp100-results.ts.
 * Run from project root: npx tsx scripts/batch-sp100.ts
 * Optional: BATCH_START=0 BATCH_COUNT=5 to run first 5 only (for testing).
 */

import { crawlDomain } from "../src/lib/crawler";
import { analyzeDomain } from "../src/lib/analyze";
import { SP100_RESULTS } from "../src/data/sp100-results";
import type { SP100Row } from "../src/data/sp100-types";
import * as fs from "fs";
import * as path from "path";

const DELAY_MS = 2000; // 2 seconds between domains to be polite
const today = new Date().toISOString().slice(0, 10);

function normalizeDomain(domain: string): string {
  const s = domain.trim();
  if (!s) return "";
  return s.startsWith("http") ? s : `https://${s}`;
}

function formatRow(row: SP100Row): string {
  const parts: string[] = [
    `companyName: ${JSON.stringify(row.companyName)}`,
    `ticker: ${JSON.stringify(row.ticker)}`,
  ];
  if (row.domain != null && row.domain !== "") parts.push(`domain: ${JSON.stringify(row.domain)}`);
  if (row.overallScore != null) parts.push(`overallScore: ${row.overallScore}`);
  if (row.categoryScores != null) {
    parts.push(
      `categoryScores: { crawlability: ${row.categoryScores.crawlability}, structuredData: ${row.categoryScores.structuredData}, parseability: ${row.categoryScores.parseability}, freshness: ${row.categoryScores.freshness}, irChecklist: ${row.categoryScores.irChecklist} }`
    );
  }
  if (row.lastScanned != null) parts.push(`lastScanned: ${JSON.stringify(row.lastScanned)}`);
  return `  { ${parts.join(", ")} }`;
}

async function main() {
  const startIdx = parseInt(process.env.BATCH_START ?? "0", 10);
  const count = parseInt(process.env.BATCH_COUNT ?? "0", 10);
  const limit = count > 0 ? count : SP100_RESULTS.length;
  const rows = SP100_RESULTS.slice(startIdx, startIdx + limit);
  const total = rows.length;
  const totalInList = SP100_RESULTS.length;

  console.log(`Batch: scanning ${total} domains (start=${startIdx}, count=${limit || "all"}). Delay ${DELAY_MS}ms between each.\n`);

  const results: SP100Row[] = [...SP100_RESULTS];
  let done = 0;
  let failed = 0;

  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    const idx = startIdx + i;
    if (!row.domain?.trim()) {
      console.log(`[${idx + 1}/${totalInList}] ${row.companyName} (${row.ticker}) — no domain, skip`);
      continue;
    }

    const url = normalizeDomain(row.domain);
    process.stdout.write(`[${idx + 1}/${totalInList}] ${row.companyName} (${row.ticker}) ${url} ... `);

    try {
      const crawlResult = await crawlDomain(url, {
        onProgress: (msg) => { /* quiet */ },
      });
      const analyzed = analyzeDomain(crawlResult, { onProgress: () => {} });

      results[idx] = {
        ...row,
        overallScore: analyzed.overallScore,
        categoryScores: analyzed.categoryScores,
        lastScanned: today,
      };
      done++;
      console.log(`OK overall=${analyzed.overallScore}`);
    } catch (e) {
      failed++;
      const msg = e instanceof Error ? e.message : String(e);
      console.log(`FAIL: ${msg}`);
      results[idx] = { ...row, lastScanned: today };
    }

    if (i < rows.length - 1) {
      await new Promise((r) => setTimeout(r, DELAY_MS));
    }
  }

  const outPath = path.join(process.cwd(), "src", "data", "sp100-results.ts");
  const header = `/**
 * S&P 100 (largest 100 companies by market cap in S&P 500) — scanner results.
 * Generated by scripts/batch-sp100.ts. Last batch run: ${today}
 */

import type { SP100Row } from "./sp100-types";

export const SP100_RESULTS: SP100Row[] = [
`;
  const footer = "\n];\n";
  const body = results.map(formatRow).join(",\n");
  fs.writeFileSync(outPath, header + body + footer, "utf8");
  console.log(`\nWrote ${outPath}. Scanned: ${done} OK, ${failed} failed.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
